export const FETCH_SPONSORSHIPS = 'FETCH_SPONSORSHIPS';
export const FETCH_SPONSORSHIPS_FAILED= 'FETCH_SPONSORSHIPS_FAILED';

export const FETCH_TILES = 'FETCH_TITLES';
export const FETCH_TILES_FAILED = 'FETCH_TILES_FAILED';